services:
  - type: web
    name: ultimo-dia
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: OPENAI_API_KEY
        sync: false


